# -*- coding: utf-8 -*-
"""All of GEN AI Basic 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVWC8LV3VqJtFG_atr-wo0vplYiL-4C7
"""

#from re import sub
x=10 # "x" is the variable, "=" is the assignment operator and "10" is the information.
# rules for namming a variable :-
#1 starting position of the variable are underscore or letter (small/capital)
my_Sub = "Python"
_mycity = "Solan"
my_Sub
_mycity
#2 remaining part of variable are underscore, letter or numbers
my_Sub1 = "GenerativeAI"
my_Sub1
#1mySub = "Science"
#1mySub
#3 Variable does not contain any Space or Symbole.
#my+Sub = "Mathematics"
#my+sub
#4 Python is case Sensitive means variable name suchas "my_Sub", "MY_SUB" are different variables.
MY_SUB = "Jawa"
my_Sub
#5 keywords =>
# 1 reserved words in the python is known as keywords.
# 2 they cannot use variable names.
# 3 these meaning already reserved.
# example => True,False,For,While,in
#code for displaying all keywords is down \/.
import keyword
keyword.kwlist
# Datatype :-
# 1 numeric
# 1.1 integer => absence of decimal point.
# example => 1,2,3,4,8 etc.
type(x)

# Floating point number--presence of decimal point.
j = 5.9
type(j)
# complex-- combination of real and imaginary number


# string-- data in the form of text
x = "Solan"
type(x)

# boolean-- it is used to store value in the form of true and false
a = True
type(a)
b = False
type(b)

# None-- define the null value means nouthing
e = None
type(e)

# Single quotes
my_sub = 'GenerativeAI'
print(my_sub)
type(my_sub)
# double quotes
my_city = "solan"
type(my_city)

# triple quotes
my_sentence = '''this is a sentence
with multiple lines'''
type(my_sentence)
# len(my_sub) -- will give length of string
len(my_sub)

# Indexing
my_sub[0] # positive indexing
my_sub[-16] # negative indexing

# slicing
my_sub = "Machine learning"
my_sub[0:10:1]

# step size is optional by  default it is one
my_sub[0:10]

my_sub[1:0:-1]
my_sub[-1: :-1]

my_sub[: :-1]
my_sub[4:]

j='hello'
type(j)

#concatinater
first_name = "Amit"
last_name = "Kumar"
full_name = first_name+" "+last_name
print(full_name)

#method in string
#lower()--this method converts string into lower case
my_sub = "Machine Learning"
my_sub.lower()
#upper -- this method cnverts string into upper case
my_sub.upper()

#count() -- this method used to count chracter
my_sub = "Machine Learning"
my_sub.count('a')

#list
my_list = [78,57,89,34,23]
type(my_list)

mixed_list = ["apple",23,3.14,True,None]
type(mixed_list)

print(my_list)

#len() -- this function finds the length of the list
len(my_list)

# positive indexing
my_list = [78,59,23,64]
print(my_list[0])
print(my_list[1])
print(my_list[2])
print(my_list[3])

# negitive indexing
my_list = [78,59,23,64]
print(my_list[-1])
print(my_list[-2])
print(my_list[-3])
print(my_list[-4])

my_list = [2,3,4,7,8,9]
my_list[0:5:1]

#step size by default is one
my_list[0:5]

my_list[0:]

my_list[:5]

my_list[: :-1]

# function in list
#min() -- this function finds the minimum number of items in list
my_list = [2,3,4,7,8,9]
min(my_list)

#max() -- this function finds the maximum number of items in list
max(my_list)

#sum() -- this function work on numerical
sum(my_list)

#sorted() -- arranging list in increasing or decreasing order
my_list = [9,7,2,3,6,10,5]
sorted(my_list, reverse = True)

#sort() -- arranging list in increasing or decreasing order
list1 = [8,6,3,2,9,10,1]
list1.sort(reverse = True)
list1

#append() -- this method add the item end of the list
my_list = [3, 45, 89, 23]
my_list.append(100)
my_list

#,extend() -- this method merge a list into another list
list1 = [90,87,65,43]
list2 = [56,45,89,60]
list1.extend(list2)
list1

#pop() -- this method remove item from the list, take index as an argument
my_list = [90,80,85,23,89]
my_list.pop()

my_list

my_list.pop(0)

#dicionary : it is the collection of key - value pair
#it is mutable type data structure by value saperated by colon and every key value pair seperated by comma and enclosed by curly braces
my_dict =  {"HP":"SHM","PU":"CHD","UP":"LUCK"}
type(my_dict)

print(my_dict)

#how to find value with help of key
print(my_dict["HP"])
print(my_dict["PU"])
print(my_dict["UP"])

#dictionary method
#keys() -- this method return the list of keys in dictionary object
my_dict.keys()

#values() -- this method returns the list of values in dictionary object
my_dict.values()

#items()- this method return the list of keys or values
list(my_dict.items())

#get() -- this method return value and take key as a argument
my_dict.get("HP")

my_dict.get("MP","Not Found")

my_dict = {"Name":"Amit","state":"HP"}
my_dict.update({"College":"Shoolini University"})
my_dict

my_dict.update({"Name":"Kritka"})
my_dict

#zip() -- this function takes pair of lists as argument and return object
name_list = ["Amit","Kritika","Roshan"]
college_list = ["Shoolini","LR","MMU"]
dict(zip(name_list,college_list))

#conditional statement
#if statement -- if condition is true then it execute
#elif statement -- if condition is true then it execute
#else statement -- if both statement, if and elif condition false then it executes
age = int(input("Enter your age "))
if age<18:
  print("you are too young to merry : ")
elif age>60:
  print("you are too old to merry")
else:
  print("we will find a perfect match for you : ")





#loop help to repeat a block of code repeatidely
my_name = "Amit"
print(my_name[0])
print(my_name[1])
print(my_name[2])
print(my_name[3])

# for loop in python is used to iterate over a sequence(string,list,tuple)

my_name = "Amit"
for i in my_name :
  print(i)

for i in range(0,5,1):
  print(i)

my_sub = "python"
for i in range (len(my_sub)):
  print(my_sub[i],"->",i)

#while loop -- is used to execute a block of code repeatedly until
# a given condition is true
i = 0
while i<5:
  print(i)
  i+=1

#loop control statement
#break--break the loop
#continue--skip current iteration
#pass -- only pass the code
i=0
while i<6:
  i+=1
  if i==3:
    break
    print(i)
  else:
    print(i)

i=0
while i<6:
  i+=1
  if i==3:
    continue
    print(i)
  else:
    print(i)

i=0
while i<6:
  i+=1
  if i==3:
    pass
    print(i)
  else:
    print(i)

#user defined functions -> it is defined user according to your need is

#user defined function without argument
def add():
  a = int(input("Enter First number : "))
  b = int(input("Enter second number : "))
  return a+b

add()

#positional argument -- positional argument are the argument that are pass to a function
#these value pass during call of the function
def calculator(a,b):
  print("Addition", a+b)
  print("Subtraction", a-b)
  print("Multiply", a*b)
  print("Division", a/b)

  return "Our calculator is complete"

print(calculator(10,5))

#default argument- these argument value given during definedva function
def area_perimeter(width = 2,hight = 4):
  area = width*hight
  perimeter = 2*(width+hight)
  return area,perimeter

area_perimeter(8)

# keyword argument that are passed to a function using the name of the argument. followed by equal sign
def intrust(p,r,t):
  i=(p*r*t)/100
  return i

intrust(r=10,t=2,p=1000)

# mixed argument
intrust(1000, t = 2, r = 10)

# intrust(p = 1000, r = 10, 2) will show error!!!

# non keyword positional variable length argument
def test(*args):
  print(args)
  print(len(args))
  print(type(args))

test(1,7,8,9,10,11)

my_tuple=(4,5,7,8)
for i in my_tuple:
  print(i)

def sum_number(*args):
  sum = 0
  for num in args:
    sum+=num
  return sum

sum_number(3,4,5,6,2)

#keyword variable length argument
#keyword variable input argument acts as a dictionary
def test(**kwargs):
  print(kwargs)
  print(len(kwargs))
  print(type(kwargs))

test(a=10,b=20,c=30)

#keyword variable length argument
#keyword variable input argument acts as a dictionary
def test(**kwargs):
  print(kwargs)
  print(len(kwargs))
  print(type(kwargs))

def pass_students(**kwargs):
  pass_student_list = []
  for name, marks in kwargs.items():
    if marks>33:
      pass_student_list.append(name)
  return pass_student_list

pass_students(A=40,b=30,c=60)

#library is the collection of function, attribute,method,property,class,file,modul and package.
#numpy numerical python
# it is use for mathematics
#data structure of numpy multidimensional array.
import numpy as np
# import is keyword which is used to import module package or library.
# as is used to name alies, it is also a keyword.
# np is the alies or nickname

#array
one_array = np.array([1,2,3])
print(one_array)

rank1_vector = np.array([1,2,3,4])
print(rank1_vector)

#ndim-find the dimension of the vector
print(rank1_vector.ndim)

#size--total number of item
print(rank1_vector.size)

print(rank1_vector.transpose())

row_vector = np.array([[1,2,3]])
print(row_vector)

print(row_vector.ndim)

print(row_vector.size)

print(row_vector.transpose())

print(row_vector)
print(row_vector.shape)

print(row_vector[0])

#two dimensional array
twod_array = np.array([[1,2,3],[8,9,2]])
print(twod_array)

print(twod_array[0])
print(twod_array[1])

print(twod_array[0][1])

print(twod_array[1][0])

import numpy as np

mat1 = np.matrix("1,2,3;4,5,6;7,8,9")
print(mat1)

zeros_array = np.zeros((3, 3),dtype = int)
print(zeros_array)

ones_array = np.ones((3,3),dtype = int)
print(ones_array)

ones_array = np.ones((3,3),dtype = int)
print(ones_array*99)
print(ones_array*100)

ones_array = np.full((3,3), 100)
print(ones_array)

my_array = np.array([1, 2,3, 4])
print(my_array)

power_array = np.power(my_array, 2)
print(power_array)

exp_data = np.exp(my_array)
print(exp_data)

print(my_array)

log_array = np.log(my_array)
print(log_array)

log2_array = np.log2(my_array)
print(log2_array)

log10_array = np.log10(my_array)
print(log10_array)



random_array = np.random.random((3, 3))
print(random_array)

randint_array = np.random.randint(1, 10, (3, 3))
print(randint_array)

# matplotlib is a python library
# it is used for data visualization
# How to import
import matplotlib.pyplot as plt
# matplotlib is a library
# pyplot is a sub module
# plt is an aliese or a nickname
import numpy as np

# line plot (1,2) & (3,4)
xpoint = np.array([1, 3])
ypoint = np.array([2, 4])
plt.plot(xpoint,ypoint)
plt.show()

cgpa = np.array([6, 6.5 , 7, 7.8 , 8.4 , 8 , 8.9 , 9 , 9.5 , 10])
package = np.array([4,4.5,6,6.5,7,7.8,8,8.9,10,12])
font1 = {"family":"Serif", "color":"blue", "size":20}
font2 = {"family":"Serif", "color":"darkred", "size":15}
plt.plot(cgpa, package,"*:g",ms = 15,mec = "red",mfc = "purple",linewidth = 4)
plt.xlabel("CGPA",fontdict=font2)
plt.ylabel("Package",fontdict=font2)
plt.title("CGPA vs Package",fontdict=font1)
plt.grid(color = "red",linestyle = ":", linewidth = 1.5)
plt.show()

# bar polt -> it is work on numerical as well as catagorical data
import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(["Apple","Banana","Orange","Watermelon"])
quantity = np.array([100,200,150,120])
color = np.array(["Red","Yellow","Orange","Green"])
plt.bar(fruit,quantity,color=color)
plt.show()

# bar polt -> it is work on numerical as well as catagorical data
import matplotlib.pyplot as plt
import numpy as np
fruit = np.array(["Apple","Banana","Orange","Watermelon"])
quantity = np.array([100,200,150,120])
color = np.array(["Red","Yellow","Orange","Green"])
plt.barh(fruit,quantity,color=color)
plt.show()

# pie plot -> it is work on numerical data as well as catagorical data
fruit_percentage = np.array([20,25,35,20])
fruit = np.array(["Apple","Banana","Orange","Watermelon"])
plt.pie(fruit_percentage,labels = fruit)
plt.legend(title="Fruit")
plt.show()

# scatter plot -> this plot represents data in point from
age_of_car = np.array([4,5,6,7,8,9,10])
speed_of_car = np.array([150,140,130,120,110,100,90])
plt.scatter(age_of_car,speed_of_car)
plt.show()

# histogram -> it showing the frequency distribution of the data
import matplotlib.pyplot as plt
import numpy as np
x = np.random.randint(40,100,(1,200))
x=x.flatten()
print(x)



plt.hist(x,bins = 20)
plt.xlabel("Data")
plt.ylabel("frequency")
plt.show()

# pandas is a python library, which is used for data manipuliation like data cleaning, data analysis, find the null value
import pandas as pd
# data structure of pandas is :-
# series -> 1 dimensional
# dataframe -> 2 dimensional
# panel -> 3 dimensional
list_of_fruit = ["Apple","Banana","Mango","Grapes"]
my_series = pd.Series(list_of_fruit, name = "Fruit")
my_series

list_of_list = [["Apple",100],["Banana",120],["Orange",150],["Water melon",80]]
df = pd.DataFrame(list_of_list, columns = ["Fruit","Quantity"])
df

df = pd.read_csv("/content/drive/MyDrive/data/imdb_data.csv")
df

# Supervised machiene learning -> it is type of machine learning, deal with labled data
# Regression based learning -> in this problum, the output feature data is contineous form
# e.g. :- House price pridiction
# e.g. :- Package Pridiction.
# supervised machine learning algorithem solved classification based problem
# 1 logistic regression
# 2 Support Vector classification.
# 3 decision tree classification.
# 4 random forest classification.

# Unsupervised machine learning -> this is one type of machine learning, in which deal with unlabel data
# Unsupervised ML Solved following type of problem
# Algorithem
# 1 K-means clustering
# 2 DBSCAN
# 3 Principle  Component Analysis (PCA)

# deep learning  it is the sub field of AI and ML, the structure is inspired by human brain
# DL -> logical structure -> neural network
# e.g. :- placement pridiction
# Forward propogation
# eg -> CGPA| iq | placed
#         10| 120| 1
#          5|  80| 0

import nltk
nltk.download('punkt')
nltk.download('punkt_tab') # Add this line to download the missing resource
from nltk.tokenize import word_tokenize

sentence = "Machine learning is fun!"
tokens = word_tokenize(sentence)

print("Tokens:", tokens)

from transformers import pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
text = """ The global shift toward renuable energy is accelerating,
driven by concerns over climate change and energy security. Solar and wind power installations have reached record levels worldwide """
summary = summarizer(text, max_length=30, min_length=10, do_sample=False)
print(summary[0]['summary_text'])

# ANN(Artificial neural network) -> Works on tabular data
# CNN(Convolutional neural network) -> Works on Image data
# RNN/LSTM(Recurrent neural network/ Long short term memory network) -> Works on Sequential data
# Encoder-Decoder --> they are type of neural network that work on sequence to sequence data (input sequence to output sequence). they are used in machine translation.
#->Encoder -> Sequence to Sequence
#->Decoder -> machine translation

# clear() -> REMOVE ALL THE ELEMENTS FROM THE LIST
a = [1,2,3,4,5]
a.clear()
print(a)
# CNN -> Convalutional neural network
# (1) -> Convalutional layer
# (2) -> pooling layer
# (3) -> Fully connected layer
# convalutional operation